spring:
  cloud:
    stream:
      function:
        definition: consumer
      rabbit:
        bindings:
          consumer-in-0:
            consumer:
              exchangeType: direct
#              autoBindDlq: true
#              queueNameGroupOnly: true
              binding-routing-key: "rabbit-processor.to.rabbit-consumer"
      bindings:
        consumer-in-0:
          destination: sample.queue
          group: consumer
          binder: rabbit
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbit:
                deliveryMode: ${DELIVERY_MODE:2}
                host: ${RABBIT_HOST:localhost}
                port: ${RABBIT_PORT:5672}
                username: ${RABBIT_USERNAME:guest}
                password: ${RABBIT_PASSWORD:guest}
                virtual-host: ${RABBIT_VHOST:/}

server:
  port: 8082
